name: Deploy Python Code
on: [workflow_dispatch, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy Python files
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.VM_HOST }}
            username: ubuntu
            key: ${{ secrets.VM_KEY }}
            port: 22
            source: "./main.py,./requirements.txt"
            target: /home/ubuntu

      - name: Install Python dependencies and run script
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: ${{ secrets.VM_HOST }}
            username: ubuntu
            key: ${{ secrets.VM_KEY }}
            port: 22
            script: |
                pip3 install flask --break-system-packages
                nohup python3 main.py > output.log 2>&1 &
      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev        
    

